package com.databreeze.enums;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    LOGIN,
    LOGOUT,
    INVITE_MEMBER,
    REMOVE_MEMBER,
    CHANGE_ROLE,
    UPLOAD_FILE,
    CONFIRM_MAPPING,
    START_IMPORT,
    CANCEL_IMPORT,
    CREATE_PAYMENT,
    PAYMENT_WEBHOOK_RECEIVED,
    PAYMENT_STATUS_UPDATED,
    ADMIN_SUSPEND_USER,
    ADMIN_UPDATE_SUBSCRIPTION,
    GENERATE_INSIGHT
}
