package com.databreeze.enums;

public enum InsightType {
    REVENUE_SPIKE,
    REVENUE_DROP,
    PROFIT_DROP,
    LOW_MARGIN_SKU,
    NEGATIVE_PROFIT_SKU,
    HIGH_REVENUE_LOW_PROFIT_SKU,
    HIGH_REFUND_RATE,
    HIGH_AD_SPEND,
    LOW_ROAS_CAMPAIGN,
    NEGATIVE_ROI_CAMPAIGN,
    MISSING_PRODUCT_COST,
    MISSING_REQUIRED_MAPPING,
    PLATFORM_PERFORMANCE_CHANGE,
    STORE_PERFORMANCE_CHANGE,
    DATA_QUALITY_WARNING
}
