package databreeze.enums;

public enum ImportJobType {
    DETECT_SCHEMA,
    SUGGEST_MAPPING,
    VALIDATE_MAPPING,
    IMPORT_MARKETPLACE_ORDER,
    IMPORT_MARKETPLACE_SETTLEMENT,
    IMPORT_ADS_PERFORMANCE,
    IMPORT_PRODUCT_COST,
    IMPORT_OPERATING_EXPENSE,
    IMPORT_MANUAL_REVENUE,
    IMPORT_MANUAL_PROFIT,
    RECALCULATE_REVENUE,
    RECALCULATE_PROFIT,
    GENERATE_INSIGHTS
}
