package databreeze.enums;

public enum InsightActionType {
    REVIEW_SKU_COST,
    UPDATE_PRODUCT_COST,
    REDUCE_AD_BUDGET,
    PAUSE_CAMPAIGN,
    INCREASE_CAMPAIGN_BUDGET,
    CHECK_REFUND_REASON,
    REVIEW_PLATFORM_FEES,
    OPTIMIZE_PRODUCT_PRICE,
    REVIEW_MAPPING,
    UPLOAD_COST_FILE,
    EXPORT_REPORT
}
